### ISSUE TITLE
'IndexError: list index out of range' on Splunk 5.0

### ISSUE THREAD

**Issue by ampledata** [eurica/splunk_app_pagerduty#2]
Just installed the pagerduty splunk app and have configured it, but it fails to work. The splunk `python.log` shows the `pagerduty.py` script is being executed, but nothing is showing up in pagerduty (API key is set). When attempting to run the script by hand with the exact same arguments that are in the `python.log` (and after setting the splunk env vars), it fails with: 

``` python
Traceback (most recent call last): 
File "/opt/splunk/bin/scripts/pagerduty.py", line 157, in <module> main() 
File "/opt/splunk/bin/scripts/pagerduty.py", line 152, in main description = details['events'][0]['_raw'] 
IndexError: list index out of range 
```

I am not certain this is the reason the app isn't working when executed by splunk though. But I couldn't find any errors from the app anywhere. This is with splunk 5.0 on ubuntu 12.04

**Comment by ampledata** [comment]
I just tested the app against Splunk 5.0.1 and alerts came through for me.

**Comment by rogerhu** [comment]
The issue is in this line of code: https://github.com/ampledata/splunk_app_pagerduty/pull/5
